workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    my-source:
        inputs:
            - location: https://www.speakeasy.com/openapi.yaml
        registry:
            location: registry.speakeasyapi.dev/speakeasy-self/speakeasy-self/my-source
targets:
    php-target:
        target: php
        source: my-source
        publish:
            packagist:
                username: $PACKAGIST_USERNAME
                token: $PACKAGIST_TOKEN
