workflowVersion: 1.0.0
sources:
    my-source:
        inputs:
            - location: https://docs.speakeasyapi.dev/openapi.yaml
targets:
    php-target:
        target: php
        source: my-source
        publish:
            packagist:
                username: $PACKAGIST_USERNAME
                token: $PACKAGIST_TOKEN
